### ISSUE TITLE
Revisión de código

### ISSUE THREAD

**Issue by FabianBravoA** [abejapower/scl-2018-05-bc-core-am#2]
Te anoto los puntos que tocamos en la revisión de hoy :

- Revisar las variables y sus nombres, recuerda usar siempre el mismo nombre para una misma variable
- No te repitas tanto, puedes hacer operaciones que haces a cada rato solo una vez y guardarla en una variable que después ocupas en reemplazo de la operación.
- Arreglar errores de sintaxis, especialmente en las funciones de String, como fromCharCode que estaba como fromCodde.

**Comment by abejapower** [comment]
ok
